export const COMPLAINT_AREA_TYPES = {
  COMMON_AREA: "Common Area",
  INDIVIDUAL_AREA: "Individual Area",
};

export const COMMON_AREAS_CATEGORIZED = {
  Building: [
    "Lobby",
    "Lift",
    "Staircase",
    "Corridor",
    "Entrance Lobby",
    "Lifts / Lift Lobby",
    "Terrace",
    "Corridors / Passage",
  ],
  Parking: [
    "Resident Parking",
    "Visitor Parking",
    "Parking Area",
  ],
  Recreation: [
    "Garden",
    "Gym",
    "Clubhouse",
    "Pool",
    "Play Area",
    "Garden / Green Area",
    "Children's Play Area",
    "Swimming Pool",
    "Community Hall",
    "Indoor Games Area",
    "Walking / Jogging Track",
  ],
  Administration: [
    "Society Office",
    "Reception",
    "Reception Area",
    "Visitor Waiting Area",
    "Seating Area",
  ],
  Utilities: [
    "Electrical Room",
    "Pump Room",
    "Generator Room",
    "Water Tank",
    "Water Tank Area",
    "Meter Room",
  ],
  Security: [
    "Main Gate",
    "Main Entrance / Gate",
    "Security Cabin",
    "CCTV Area",
    "Fire Safety Area",
    "Fire Safety Equipment Area",
  ],
  Maintenance: [
    "Garbage Area",
    "Garbage Collection Area",
    "Maintenance Room",
    "Open Common Area",
  ],
};

export const INDIVIDUAL_AREAS_LIST = [
  "Flat / Apartment",
  "Private Balcony",
  "Private Terrace",
  "Private Garden",
  "Private Parking Slot",
  "Covered Parking",
  "Open Parking",
  "Basement Parking Slot",
  "Garage",
  "Store Room",
  "Servant Room",
  "Utility Area",
  "Dry Balcony",
  "Attached Terrace",
  "Private Courtyard",
  "Private Lobby",
  "Private Entrance Area",
  "Visitor Parking Slot Assigned to Flat",
  "EV Charging Slot",
  "Bike / Two-Wheeler Parking Slot",
  "Bicycle Parking Slot",
  "Additional Storage Area",
  "Meter Space Assigned to Unit",
  "AC Outdoor Unit Space",
  "Washing / Laundry Area",
  "Kitchen Utility Area",
  "Garden Patch Assigned to Flat",
  "Terrace Garden Area",
  "Pet Area Assigned to Unit",
];
